title: Hanzhi Guo
description: ^-^
author: Hanzhi Guo
avatar: /logo.png
location: Beijing, China
email: guohzleb@163.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10


# Jekyll SEO Tag (Optional)
# =========================

logo: logo.png
social:
  name: Hanzhi Guo
  links:
    - https://github.com/Haza628
google_site_verification: QM-vReXXsWbpS1SqwR5FehBi1v5N8LbADQWMFpF6L5E
lang: en
