title: Hanzhi Guo
description: Beyond the horizon, countless paths await.
author: Hanzhi Guo
avatar: /logo.png
email: guohzleb@163.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: Hanzhi Guo
  card: summary
logo: logo.png
social:
  name: Hanzhi Guo
  links:
    - https://github.com/Haza628
google_site_verification: QM-vReXXsWbpS1SqwR5FehBi1v5N8LbADQWMFpF6L5E
lang: en
